# Generated by Django 4.0.4 on 2022-04-20 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('nationalId', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=300)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('licenseCategory', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('B', 'booked'), ('NB', 'not booked')], default='NB', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=3, default='0', max_digits=20)),
                ('registration_plate', models.CharField(default='', max_length=200)),
                ('vehicle_status', models.CharField(choices=[('B', 'Booked'), ('NB', 'Not Booked')], default='NB', max_length=2)),
                ('insurance_status', models.CharField(choices=[('U', 'Updated'), ('NU', 'Not Updated')], default='NU', max_length=2)),
                ('no_of_km_travelled', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('fuel_type', models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel')], default='P', max_length=1)),
                ('mileage', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('vehicle_type', models.CharField(choices=[('P', 'Passenger'), ('T', 'Truck'), ('C', 'Construction')], default='P', max_length=1)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='vehicle_image')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeredDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('S', 'solved'), ('NS', 'not solved')], default='NS', max_length=2)),
                ('issue', models.CharField(max_length=1000)),
                ('registeredUser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleapp1.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bookingDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('startDate', models.DateTimeField(verbose_name='Start date ')),
                ('endDate', models.DateTimeField(verbose_name='end date ')),
                ('securityDeposit', models.IntegerField()),
                ('status', models.CharField(choices=[('B', 'booked'), ('NB', 'not booked'), ('E', 'expired')], default='NB', max_length=2)),
                ('discountId', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('duration', models.CharField(default='Error', max_length=100)),
                ('allottedDriver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicleapp1.driver')),
                ('allottedUser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleapp1.vehicle')),
            ],
        ),
    ]
